import Head from 'next/head'
import React, { ReactNode } from 'react'
import Header from './Header'

type Props = {
	children: ReactNode
}

const Layout = ({children}: Props) => {
  return (
	 <main>
		<Head>
        <title>OussamaDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
		<main className='mx-auto container'>
			<Header />
			<main>{children}</main>
			{/* <Footer /> */}
		</main>
	 </main>
  )
}

export default Layout